variable "Azure_Recovery_Services_Vault_Name" {}
variable "Location" {}
variable "RGName_Backup" {}
variable "Storage_Mode_Type" {}
variable "Backup_Policy_Name" {}
variable "Time_Zone" {}
variable "Backup_Frequency" {}
variable "Backup_Time" {}
variable "Daily_Retention" {}
variable "Weekly_Retention" {}
variable "Weekly_Retention_Days" {}
variable "Monthly_Retention" {}
variable "Monthly_Retention_Days" {}
variable "Monthly_Retention_Weeks" {}
variable "Yearly_Retention" {}
variable "Yearly_Retention_Day" {}
variable "Yearly_Retention_Week" {}
variable "Yearly_Retention_Month" {}