variable "RGName_Networking" {}
variable "Internal_Next_Hop" {}
variable "External_Next_Hop" {}
variable "Location" {}
variable "Virtual_Desktop_Subnet_Id" {}
variable "Internal_Subnet_Id" {}
variable "Server_Subnet_Id" {}
variable "Storage_Subnet_Id" {}
variable "Route_Table_Name" {}
variable "Route_Name" {}