variable "Location" {}
variable "RGName_Networking" {}
variable "external_subnet_id" {}
variable "internal_subnet_id" {}
variable "Fortigate_Public_IP_Name" {}
variable "External_Fortigate_NIC_Name" {}
variable "External_Fortigate_NIC_Config_Name" {}
variable "External_Fortigate_Private_Address_Allocation" {}
variable "Internal_Fortigate_NIC_Name" {}
variable "Internal_Fortigate_NIC_Config_Name" {}
variable "Internal_Fortigate_Private_Address_Allocation" {}
variable "Fortigate_Public_IP_Allocation_Method" {}